### ISSUE TITLE
import the driver in pure html/js way

### ISSUE THREAD

**Issue by gasolin** [esphen/localforage-webExtensionStorage-driver#1]
Is there any pure html/js way to import the driver?

I guess `import...from...` syntax is not supported without builder
```
import localforage from 'localforage';
```

It might help to share an example extension project for reference.

**Comment by eliihen** [comment]
> I guess import...from... syntax is not supported without builder

Correct. I created this for my project, RESTED, which uses it [here](https://github.com/esphen/RESTED/blob/react-rewrite/src/index.js) via wepack.

I agree that there should be an example of how to use it in a simple js way. I'll put that on my TODO list

**Comment by eliihen** [comment]
I added an example of this to the README
